### ISSUE TITLE
Broken link in readme.md 

### ISSUE THREAD

**Issue by ibmchas** [IBM/ibmcloud-cos-cli#1]
Minor editorial issue 

The link reference under Example CLI usage appears to be broken 

- (For information on other commands, go to our plug-in [page](url).)

**Comment by wbhuberIBM** [comment]
@ibmchas - thanks for opening this ticket.  The fix for the link will be in the next patch release.  

Tracking this internally here: CSAFE-68546

**Comment by wbhuberIBM** [comment]
@ibmchas - the plug-in page on README has been fixed in Version 1.1.3.  Closing this issue.
