### ISSUE TITLE
Mismatch Between JSON and Text Results in bucket-location-get Command

### ISSUE THREAD

**Issue by OdedViner** [IBM/ibmcloud-cos-cli#11]
The ibmcloud cos `bucket-location-get` command produces inconsistent outputs between JSON and text formats.

Run the JSON output command:
```
oviner~$ ibmcloud cos bucket-location-get --bucket clacroix-cos-testing --output json
{
  "LocationConstraint": "us-south-smart"
 }
```

Run the plain text command:
```
oviner~$ ibmcloud cos bucket-location-get --bucket clacroix-cos-testing
OK
Details about bucket clacroix-cos-testing:
Region: us-south
Class: Smart
```

**Comment by IBMalok** [comment]
@OdedViner  - This is expected behavior. 
Plain text is customized output to display the user while json represents the actual backend output.
Hence closing the ticket.
