### ISSUE TITLE
Add ppc64le support to cloud-object-storage plugin

### ISSUE THREAD

**Issue by mamitchl** [IBM/ibmcloud-cos-cli#2]
Currently, the cloud-object-storage plugin does not work for ppc64le even though the ibmcloud CLI is supported:
```
ubuntu@ubuntu:~$ ibmcloud plugin install cloud-object-storage
Looking up 'cloud-object-storage' from repository 'IBM Cloud'...
FAILED
Could not find compatible binary to install for plug-in cloud-object-storage.
```
Can it be built for ppc64le?

**Comment by wbhuberIBM** [comment]
@mamitchl - I built and submitted the ppc64le binary file for the current CLI version (1.1.2) to you on Slack.  The binary installation worked for you and you were able to run COS CLI commands without an issue.  This is the short term support we can do until further notice. 

For long term updates to include this platform, we are keeping track of the changes in this ticket: CSAFE-68607

**Comment by mamitchl** [comment]
This is now available from https://plugins.cloud.ibm.com/ui/repository.html and we've confirmed that it works. Thank you!
