### ISSUE TITLE
Upload a directory using ibmcloud cli

### ISSUE THREAD

**Issue by prasad-1729** [IBM/ibmcloud-cos-cli#3]
Hi

Is there any way to upload a directory(multiple files) to COS directly from local? Help me this...
I can see the aspera will work...it work only in systems...
If servers like jenkins....this aspera wont work..I guess..

Thanks!!

**Comment by wbhuberIBM** [comment]
@prasad-1729 - currently, there are no commands in COS Plugin (ibmcloud cos) that support uploading a directory with multiple files to COS directly from a local machine.  For now, you can create a bash script that recursively puts object to the bucket using the CLI from inside a directory.  Each loop will pick up the object name in the directory and tag it as the key for the ```put-object``` command. 

```ibm-cloud cos put-object --bucket <bucket_name> --key <object_name>```
