### ISSUE TITLE
Show progress while downloading an object

### ISSUE THREAD

**Issue by akashrajkn** [IBM/ibmcloud-cos-cli#6]
Hi, thank you for the plugin and the cli :)

When downloading objects using cli, it would be nice to show a progress bar. Will it be supported in the future? At the moment only the message "OK" is shown after the download has completed (which is not informative if the object is large)

Relevant command: 
```
ibmcloud cos object-get --bucket <bucket> --key <key>
```

**Comment by IBMeric** [comment]
Thanks for your report. I've opened COSSDK-87913 to investigate this. The same thing will happen on `object-put`, etc., so I added that as well. FYI, there may be limitations in the S3 backend that may not give insight into the progress of the operation.

This ticket may take a while to investigate, so I'm going to close it for metric tracking purposes. It sounds like a good usability improvement if it can be done.

**Comment by akashrajkn** [comment]
Thank you for the quick response.
