### ISSUE TITLE
config location

### ISSUE THREAD

**Issue by gilv** [IBM/ibmcloud-cos-cli#7]
when i use CLI to configure COS client
`ibmcloud cos config` where is the config file generated? I thought it under ~/. but nothing created there...
`aws config` for example generated config file under ~/,aws

**Comment by IBMalok** [comment]
@gilv - it will be generated under `~/.bluemix/config.json`

**Comment by arnabm28** [comment]
@gilv Did the above location solves the config file issue for you. In case it working for you can you please close the issue.

Thanks
